# Generated by Django 5.2.11 on 2026-02-12 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram')], max_length=16)),
                ('external_id', models.CharField(max_length=128)),
                ('handle', models.CharField(blank=True, default='', max_length=128)),
                ('url', models.URLField(blank=True, default='')),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('added_by', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.BigIntegerField(unique=True)),
                ('tg_chat_id', models.BigIntegerField()),
                ('timezone_str', models.CharField(default='Europe/Moscow', max_length=64)),
                ('tz_source', models.CharField(choices=[('default', 'Default'), ('manual', 'Manual'), ('location', 'Location')], default='default', max_length=16)),
                ('limits_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField()),
                ('window_days', models.IntegerField(default=30)),
                ('n_items', models.IntegerField(default=30)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='tracking.competitor')),
            ],
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram')], max_length=16)),
                ('external_id', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField()),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='tracking.competitor')),
            ],
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('views', models.BigIntegerField()),
                ('likes', models.BigIntegerField(blank=True, null=True)),
                ('comments', models.BigIntegerField(blank=True, null=True)),
                ('shares', models.BigIntegerField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='tracking.contentitem')),
            ],
        ),
        migrations.CreateModel(
            name='SeedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_input', models.TextField()),
                ('detected_platform', models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram')], default='', max_length=16)),
                ('canonical_url', models.URLField(blank=True, default='')),
                ('niche_keywords', models.JSONField(blank=True, default=list)),
                ('niche_source', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_profiles', to='tracking.tguser')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('times', models.JSONField(blank=True, default=list)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='tracking.tguser')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('failed', 'Failed')], default='created', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tracking.tguser')),
            ],
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_runs', to='tracking.tguser')),
            ],
        ),
        migrations.AddField(
            model_name='competitor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='tracking.tguser'),
        ),
        migrations.AddConstraint(
            model_name='contentitem',
            constraint=models.UniqueConstraint(fields=('competitor', 'platform', 'external_id'), name='uniq_competitor_platform_external'),
        ),
        migrations.AddIndex(
            model_name='metricsnapshot',
            index=models.Index(fields=['content_item', 'captured_at'], name='tracking_me_content_f519ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='competitor',
            constraint=models.UniqueConstraint(fields=('user', 'platform', 'external_id'), name='uniq_user_platform_external'),
        ),
    ]
