# Generated by Django 5.2.11 on 2026-02-12 08:41

import tracking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='timezone_str',
            field=models.CharField(default=tracking.models._default_timezone_str, max_length=64),
        ),
    ]
