# Generated by Django 5.2.11 on 2026-02-12

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor) -> None:
    """
    Move from per-user competitors to shared competitors + per-user link table.

    - Create UserCompetitor rows from legacy Competitor.user/added_by/is_active.
    - De-duplicate Competitor rows by (platform, external_id).
    - De-duplicate ContentItem rows by (platform, external_id) and merge MetricSnapshots.
    """
    Competitor = apps.get_model("tracking", "Competitor")
    UserCompetitor = apps.get_model("tracking", "UserCompetitor")
    CompetitorBaseline = apps.get_model("tracking", "CompetitorBaseline")
    ContentItem = apps.get_model("tracking", "ContentItem")
    MetricSnapshot = apps.get_model("tracking", "MetricSnapshot")

    competitors = list(Competitor.objects.all().order_by("id"))
    if not competitors:
        return

    canon_by_key: dict[tuple[str, str], int] = {}
    for comp in competitors:
        key = (comp.platform, comp.external_id)
        canon_by_key.setdefault(key, comp.id)

    # Create/refresh user links pointing to the canonical competitor row for each (platform, external_id).
    for comp in competitors:
        key = (comp.platform, comp.external_id)
        canon_id = canon_by_key[key]
        UserCompetitor.objects.update_or_create(
            user_id=comp.user_id,
            competitor_id=canon_id,
            defaults={
                "added_by": comp.added_by,
                "is_active": comp.is_active,
            },
        )

    # Merge competitor duplicates: move baselines + content items to the canonical competitor and delete dup rows.
    for comp in competitors:
        key = (comp.platform, comp.external_id)
        canon_id = canon_by_key[key]
        if comp.id == canon_id:
            continue

        CompetitorBaseline.objects.filter(competitor_id=comp.id).update(competitor_id=canon_id)
        ContentItem.objects.filter(competitor_id=comp.id).update(competitor_id=canon_id)

        canon = Competitor.objects.filter(id=canon_id).first()
        if canon is not None:
            changed = False
            if not canon.handle and comp.handle:
                canon.handle = comp.handle
                changed = True
            if not canon.url and comp.url:
                canon.url = comp.url
                changed = True
            if not canon.display_name and comp.display_name:
                canon.display_name = comp.display_name
                changed = True
            if comp.meta:
                merged = dict(canon.meta or {})
                merged.update(comp.meta or {})
                if merged != canon.meta:
                    canon.meta = merged
                    changed = True
            if changed:
                canon.save()

        Competitor.objects.filter(id=comp.id).delete()

    # De-duplicate content items by (platform, external_id) and merge snapshots.
    items = list(ContentItem.objects.all().order_by("id"))
    canon_item_by_key: dict[tuple[str, str], int] = {}
    for item in items:
        key = (item.platform, item.external_id)
        canon_item_id = canon_item_by_key.get(key)
        if canon_item_id is None:
            canon_item_by_key[key] = item.id
            continue
        MetricSnapshot.objects.filter(content_item_id=item.id).update(content_item_id=canon_item_id)
        ContentItem.objects.filter(id=item.id).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0002_alter_tguser_timezone_str"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCompetitor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("added_by", models.CharField(choices=[("manual", "Manual"), ("auto", "Auto")], default="manual", max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_links",
                        to="tracking.competitor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitor_links",
                        to="tracking.tguser",
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="contentitem",
            name="uniq_competitor_platform_external",
        ),
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="competitor",
            name="uniq_user_platform_external",
        ),
        migrations.RemoveField(
            model_name="competitor",
            name="added_by",
        ),
        migrations.RemoveField(
            model_name="competitor",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="competitor",
            name="user",
        ),
        migrations.AddField(
            model_name="competitor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="seedprofile",
            name="niche_source",
            field=models.CharField(
                choices=[("auto", "Auto"), ("manual", "Manual")], default="manual", max_length=16
            ),
        ),
        migrations.AddConstraint(
            model_name="competitor",
            constraint=models.UniqueConstraint(fields=("platform", "external_id"), name="uniq_platform_external"),
        ),
        migrations.AddConstraint(
            model_name="contentitem",
            constraint=models.UniqueConstraint(fields=("platform", "external_id"), name="uniq_platform_content_external"),
        ),
        migrations.AddConstraint(
            model_name="usercompetitor",
            constraint=models.UniqueConstraint(fields=("user", "competitor"), name="uniq_user_competitor"),
        ),
    ]
