# Generated by Django 5.2.11 on 2026-02-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_shared_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='running_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
