# Generated by Django 5.2.11 on 2026-03-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_schedule_is_running_schedule_running_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='tg_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
