# Generated by Django 5.2.11 on 2026-03-25 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_schedule_is_running_schedule_running_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLinkedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram')], max_length=16)),
                ('external_id', models.CharField(max_length=128)),
                ('handle', models.CharField(blank=True, default='', max_length=128)),
                ('url', models.URLField(blank=True, default='')),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('seed', 'Seed'), ('auto', 'Auto'), ('manual', 'Manual')], default='manual', max_length=16)),
                ('is_seed', models.BooleanField(default=False)),
                ('match_signals', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to='tracking.tguser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'platform'), name='uniq_user_linked_platform')],
            },
        ),
    ]
