# Generated by Django 5.2.11 on 2026-03-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_tguser_tg_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='tg_first_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tguser',
            name='tg_language_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tguser',
            name='tg_last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
