# Generated by Django 5.2.11 on 2026-03-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_tguser_tg_first_name_tguser_tg_language_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='limits_json',
        ),
    ]
